### ISSUE TITLE
how to use json code with wp?

### ISSUE THREAD

**Issue by vlaked** [denniske/wp-monero-miner#1]

**Comment by denniske** [comment]
which json code?

**Comment by vlaked** [comment]
i want to implement the json code that is in the coinhive http api but im not sure if it already exists within the wp plugin files
thanks for such a fast response!

**Comment by denniske** [comment]
There is no wrapper for the coinhive API. But you can go to "Appearance > Widgets" and put the widgets "Monero Miner Toplist" and "Monero Miner User" into your sidebar. These widgets show information about the users that have created an account on your wordpress page.

Please tell me which API calls and for what purpose you want to use. Then I can maybe write a PHP Wrapper or Widget for it.

**Comment by vlaked** [comment]
yes i wanted to add the miner dashboard, im using the widgets and they work properly

for example if i made a pool i could not find how to delete the hashes of a user, for example for users who make withdrawals, but its inside the api, i actually dont understand what does it mean that theres no wrapper for the coin hive api , but for example for user withdrawals i feel is userfull too

https://coinhive.com/documentation/http-api

/user/withdraw

**Comment by vlaked** [comment]
i dont find this tools in the plugin, but the plugin works perfet

/user/reset
/user/withdraw
/stats/history
/stats/pool
/stats/user

i was wondering if i could see the info of coinhive pool the graph in my site but mostly im interested in the json code

Maybe more widgets for this tools?

https://coinhive.com/documentation/http-api

**Comment by vlaked** [comment]
im using the widgets and they work perfectly

**Comment by denniske** [comment]
I can create some more widgets for the http api. 

What exactly do you want to create with it? Creating a mining pool is not that easy. But of course there may be other ways to reward tour visitors for mining on your site. Please send the website name to wpmonerominer@gmail.com so that I can better understand what your site is about and what you are trying to achieve.

**Comment by vlaked** [comment]
i also wanted to ask if the code works for many pc or phones at the time i will send you a email with my website

**Comment by denniske** [comment]
The miner will run for all users that are on your website. It fill run for desktop and mobile.  You can specify mining speed (throttle) for desktop and mobile in settings. I will take a look at your website later.

**Comment by vlaked** [comment]
ok i did not got a resonse for the question i was making so now im making a
new question,

i want to know what is happening with my i7 with an r9 380, it is giving me
speeds as low of 25 hashes/s, why might this be? sometimes it goes up to 70
hashes but this is the 5% of the time, i want to know what might be going
on. and i want to know if i can have an exact number of hashes that you are
making?

2017-10-17 9:57 GMT+02:00 Dennis Keil <notifications@github.com>:

**Comment by vlaked** [comment]
i will rephrase the fisrt question too, if there are 3 users in my site,
and for example each user wants to use 3 computers but each user needs to
be logged in each computer, does the code support 3 computers for each user
at the same time?


2017-10-21 9:44 GMT+02:00 Vladimir Perez <vladaca88@gmail.com>:

**Comment by denniske** [comment]
If a visitor can login in to your site from 3 different computers then it will work. I think wordpress does support multiple logins from different computers.

Regarding the hash rate, I will take a look at this later.

**Comment by vlaked** [comment]
Thank you, i will be patient, i understand you are into a lot of work, but i hope it does not take too long because its an energy waste by my side... 

i will continue posting here the issues i have, my team tested mining with 2 different hardware at the same time, a user tested with a mac laptop and a samsung phone at the same time and the user was disconected at all from mining when the second mining device was activated (widgets had the hash rate, but the coinhive dashboard lost both hardware signals from the user).
