### ISSUE TITLE
Hash rate very low

### ISSUE THREAD

**Issue by vlaked** [denniske/wp-monero-miner#2]
im using a corei7 and i get around 30 hashes/s.

**Comment by vlaked** [comment]
background is set up to 3% in my site but when i activate it or deactivate it theres a change of around 30 to 40 hashes, but when i deactivate it miner tokens dont go up it works at 70 hashes/s my i7 but tokens are not granted.

**Comment by denniske** [comment]
I currently very busy developing the next version of the plugin but I will check back when I have time.

**Comment by vlaked** [comment]
Hi aggain, i have a question, im not sure if i have something going on with tokens, im mining as admin of the site and speed of the site is till not going well, im doing a background mining of 3% but i dont feel the value changes, if i do mining in the site the number of tokens is lower than expected to miners, also im not sure if im claiming part of the users tokens.

Thanks in advance for the help.

**Comment by vlaked** [comment]
i wanted to make another question, do you take share of the blocks that a site might find? is it for sites only or you take a % of them.

**Comment by vlaked** [comment]
so no comment at all about blocks?

**Comment by vlaked** [comment]
is this a scam?

**Comment by vlaked** [comment]
coin hive tells that a corei7 is 90 hashes, so i get 30 hashes, this must be a scam, thanks for everything, im leaving you 1 star.

**Comment by denniske** [comment]
I have provided a benchmark here:
https://wordpress.org/support/topic/hash-speed-drain/

For the blocks please read coinhive.com "Fair Payouts" section:
"Unlike a traditional mining pool, this rate is fixed, regardless of actual blocks found and the luck involved finding them."
The same applies for cryptoloot and also for pool mining. I do not have information about found blocks and it does not matter. You get a fixed payout rate for a number of hashes which is fair. There are no hashes lost and I do not claim more hashes than I should.

If you still think that there is something wrong with the plugin please post a detailed log or video with the miner plugin running on your page for at least 30min. I will take a look at that.

**Comment by vlaked** [comment]
sure ill spend a lot of time for you to later tell me sorry i dont have time im very bussy, nah man, im done with this
