### ISSUE TITLE
Payment Processing Questions

### ISSUE THREAD

**Issue by DerekPadula** [denniske/wp-monero-miner#6]
Hello. I am the first person to reach the 0.1 XMR payout threshold, and I have questions about the payment. 

How I will be notified that the payment has been sent and that I've received it?

MyMonero says my account is over 90,000 blocks behind the current block, so will I have to wait for that many blocks in order for my balance to increase? If so, that could take weeks or months.

Will I receive the full balance of just over 0.1, or will there be a fee? I feel like the dev fee that you take from my hash should cover the transfer expense. The slowest and most inexpensive transfer option is fine.

I have disabled the miner until I hear back. I want to make sure the first payment goes through. 

In any case, congrats to you for making this plugin and getting your share of my website's hash. And congrats to me for being the first to earn a payout! I installed it on October 13, 2017, so it took exactly 3 months to earn 0.1 XMR.

Thank you.

**Comment by denniske** [comment]
Hi. Thank you for pool mining with the WP Monero Miner.

I will cover the transaction fee as you are the first to earn a payout! Probably I will keep this up for the next users/payouts also.

The amount of 0.1 XMR has been transferred to your address 46zvjUk6ce..
Txid: aa7d1c1db3d3fed74c8a584fba4995e83abb13345cd75dee78a3122145a902f3

Don't worry about MyMonero saying your account is 90.000 blocks behind. I will catch up quickly. I had that once and it catched up in less then a few days.

Please give feedback when you have received the XMR.

**Comment by DerekPadula** [comment]
I received the full 0.1. Thank you!

For the sake of others reading this, please clarify how the payouts work. Are they automatic? Or are you checking in every so often to see if an address has gone past 0.1, and then again at 0.2, 0.3, etc? 

You were right about MyMonero. It's already in sync.

**Comment by denniske** [comment]
At the moment the payouts are manual. I am checking the pool list daily.

**Comment by denniske** [comment]
If you are satisfied with the plugin functionality I would appreciate a review at the wordpress plugin repository :)
https://wordpress.org/support/plugin/wp-monero-miner-using-coin-hive/reviews/
